filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
  fields:
    nginx: true
output.elasticsearch:
  hosts: ["192.168.1.41:9200"]
  username: 'elastic'
  password: 'iammajid'
  index: 'filebeat'
  log_metric: "my_metric"
  log_metric_fields:
    - host
    - source
    - timestamp
    - message

